package pool

type EnumResourcePoolCreateDatacenter_tier int

const (
	EnumResourcePoolCreateDatacenter_tier1 EnumResourcePoolCreateDatacenter_tier = 1
	EnumResourcePoolCreateDatacenter_tier2 EnumResourcePoolCreateDatacenter_tier = 2
	EnumResourcePoolCreateDatacenter_tier3 EnumResourcePoolCreateDatacenter_tier = 3
	EnumResourcePoolCreateDatacenter_tier4 EnumResourcePoolCreateDatacenter_tier = 4
)
