package main

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"github.com/gorilla/mux"
	"github.com/justinas/alice"
	"net/http"
)

// ProvidersInterface is interface for /providers root endpoint
type ProvidersInterface interface { // ListNodes is the handler for GET /providers/{providerid}/resource_pools/nodes
	// List all nodes
	ListNodes(http.ResponseWriter, *http.Request)
	// DeletePoolid is the handler for DELETE /providers/{providerid}/resource_pools/{poolid}
	// Delete poolid
	DeletePoolid(http.ResponseWriter, *http.Request)
	// GetPoolid is the handler for GET /providers/{providerid}/resource_pools/{poolid}
	// Get detail view about poolid
	GetPoolid(http.ResponseWriter, *http.Request)
	// UpdatePoolid is the handler for PUT /providers/{providerid}/resource_pools/{poolid}
	// Update poolid
	UpdatePoolid(http.ResponseWriter, *http.Request)
	// ListProvideridresourcePools is the handler for GET /providers/{providerid}/resource_pools
	// List all provideridresource_pools
	ListProvideridresourcePools(http.ResponseWriter, *http.Request)
	// CreateProvideridresourcePool is the handler for POST /providers/{providerid}/resource_pools
	// Create a new provideridresource_pool
	CreateProvideridresourcePool(http.ResponseWriter, *http.Request)
	// ListProviders is the handler for GET /providers
	// List all providers
	ListProviders(http.ResponseWriter, *http.Request)
}

// ProvidersInterfaceRoutes is routing for /providers root endpoint
func ProvidersInterfaceRoutes(r *mux.Router, i ProvidersInterface) {
	r.HandleFunc("/providers/{providerid}/resource_pools/nodes", i.ListNodes).Methods("GET")
	r.Handle("/providers/{providerid}/resource_pools/{poolid}", alice.New(NewOauth2itsyouonlineMiddleware([]string{"user:memberof:org"}).Handler).Then(http.HandlerFunc(i.DeletePoolid))).Methods("DELETE")
	r.HandleFunc("/providers/{providerid}/resource_pools/{poolid}", i.GetPoolid).Methods("GET")
	r.Handle("/providers/{providerid}/resource_pools/{poolid}", alice.New(NewOauth2itsyouonlineMiddleware([]string{"user:memberof:org"}).Handler).Then(http.HandlerFunc(i.UpdatePoolid))).Methods("PUT")
	r.HandleFunc("/providers/{providerid}/resource_pools", i.ListProvideridresourcePools).Methods("GET")
	r.Handle("/providers/{providerid}/resource_pools", alice.New(NewOauth2itsyouonlineMiddleware([]string{"user:memberof:org"}).Handler).Then(http.HandlerFunc(i.CreateProvideridresourcePool))).Methods("POST")
	r.HandleFunc("/providers", i.ListProviders).Methods("GET")
}
