package main

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"github.com/gorilla/mux"
	"net/http"
)

// SearchInterface is interface for /search root endpoint
type SearchInterface interface { // Get is the handler for GET /search
	// Search for resource pools.
	Get(http.ResponseWriter, *http.Request)
}

// SearchInterfaceRoutes is routing for /search root endpoint
func SearchInterfaceRoutes(r *mux.Router, i SearchInterface) {
	r.HandleFunc("/search", i.Get).Methods("GET")
}
