#%RAML 1.0
title: "Directory service"
description: "The directory service API let you register and explorer all the service accessible in the G8OS GRID"
version: 0.0.1
mediaType: application/json
baseUri: https://discovery.gig.tech

securitySchemes:
  itsyouonline: !include https://raw.githubusercontent.com/Jumpscale-Cockpit/raml-definitions/master/securityScheme/iyo.raml

resourceTypes:
  collection: !include https://raw.githubusercontent.com/Jumpscale-Cockpit/raml-definitions/master/resourceTypes/collection.raml
  listing: !include https://raw.githubusercontent.com/Jumpscale-Cockpit/raml-definitions/master/resourceTypes/listing.raml
  member: !include https://raw.githubusercontent.com/Jumpscale-Cockpit/raml-definitions/master/resourceTypes/member.raml

traits:
  paginated: !include https://raw.githubusercontent.com/Jumpscale-Cockpit/raml-definitions/master/traits/pagination.raml
  searchable:
    queryParameters:
      longitute:
        type: number
        format: float
        description: Search by geographical coordinates, mutualy exclusive with address
      lattitude:
        type: number
        format: float
        description: Search by geographical coordinates, mutualy exclusive with address
      address:
        type: string
        description: Search by address, mutualy exclusive with longitute and lattitude
      min_cu:
        type: integer
        description: Filter by minimum amount of compute unit available in the pool
      min_su:
        type: integer
        description: Filter by minimum amount of storage unit available in the pool
      min_tu:
        type: integer
        description: Filter by minimum amount of transfer unit available in the pool
      uptime:
        type: number
        format: float
        description: Filter based on the uptime of the pool
      network_speed:
        type: integer
        description: Filter based on network speed in MiB/s
      network_redundant:
        type: boolean
        description: Filter based the network connection
      currency:
        enum: [euro, usb, hr_index]
        description: Filter based on the currency accepted
      datacenter_tier:
        enum: ["1", "2", "3", "4"]
        description: Filter based on the type of tier.

types:

  Provider:
    properties:
      name:
        type: string
        pattern: ^\w+$
      description:
        type: string
      website_url:
        type: string
      email:
        type: string
        # pattern: TODO
      telephone:
        type: string
        # pattern: TODO

  Pricing:
    properties:
      min_nr_months:
        type: integer
      cu:
        type: integer
        description: Compute Unit
      su:
        type: integer
        description: Storage Unit
      tu:
        type: integer
        description: Transfer Unit

  Location:
    properties:
      name:
        type: string
        pattern: ^\w+$
      description:
        type: string
      remarks:
        type: string
      longitute:
        type: number
        format: float
      lattitude:
        type: number
        format: float
      address:
        type: string
        #pattern: TODO

  Node:
    properties:
      uid:
        type: string
        pattern: ^\w+$
        description: gloal unique ID
      description:
        type: string
      remarks:
        type: string
      nr_cu:
        type: integer
        description: Amount of compute unit available in the node
      nr_su:
        type: integer
        description: Amount of storage unit available in the node
      nr_tu:
        type: integer
        description: Amount of transfer unit available in the node

  PoolQuality:
    properties:
      uptime:
        type: integer
        description: |
          Uptime of the service in percent
      down_periods:
        description: |
          Last time the service was down
        type: array
        items:
          properties:
            begin:
              type: datetime
            duration:
              type: integer
              description: |
                duration of the downtime in minute
      average_restauration_time:
        type: integer
        description: |
          Average number of minute before the service come back up after a problem occurs.

  ResourcePoolCreate:
    properties:
      network_speed:
        type: integer
        description: Network speed in MiB/s
      network_redundant:
        type: boolean
        description: If the network connection is redundant or not
      ipv4_nr_pub:
        type: integer
        description: Number of public IPv4 addresses
      ipv4_nr_enabled:
        type: boolean
      ipv6_nr_enabled:
        type: boolean
      pricing_currency:
        enum: [euro, usb, hr_index]
      datacenter_tier:
        enum: ["1", "2", "3", "4"]
        description: See tier definitions #TODO put link
      datacenter_uptime_sla_min:
        type: number
        format: float
        description: uptime guaranteed per month
      cu_planned:
        type: integer
        description: Amount of compute unit that will eventually be added to this pool
      su_planned:
        type: integer
        description: Amount of storage unit that will eventually be added to this pool
      tu_planned:
        type: integer
        description: Amount of transfer unit that will eventually be added to this pool
      cu_max:
        type: integer
        description: Amount of compute unit maximum this pool will ever reach
      su_max:
        type: integer
        description: Amount of storage unit this pool will ever reach
      tu_max:
        type: integer
        description: Amount of transfer unit this pool will ever reach

  ResourcePool:
    type: ResourcePoolCreate
    properties:
      provider:
        type: string
        description: ID of the provider owning this pool
      quality:
        type: PoolQuality



/providers:
  type: listing
  get:
    is: [ paginated ]
  /resource_pools:
    type: collection
    get:
      is: [ paginated, searchable ]
    post:
      securedBy: [ itsyouonline: {scopes: ["user:memberof:org"] } ]
    /{poolid}:
      type: member
      delete:
        securedBy: [ itsyouonline: {scopes: ["user:memberof:org"] } ]
      put:
        securedBy: [ itsyouonline: {scopes: ["user:memberof:org"] } ]
    /nodes:
      type: listing
      get:
        is: [ paginated ]
/search:
  get:
    description: |
      Search for resource pools.
    is: [ paginated, searchable ]
    queryParameters:
      provider:
        type: string
        description: Filter based on the provider
    responses:
      200:
        body:
          ResourcePool
